import csv
import io
import json
import os
import smtplib
import threading
import time
import urllib.request
from http.server import HTTPServer, BaseHTTPRequestHandler
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.utils import formatdate, make_msgid

SHEET_EXPORT_URL = os.environ.get(
    "SHEET_EXPORT_URL",
    "https://docs.google.com/spreadsheets/d/1cZ7N52nVw9yy3QpsMh1Kra9-yk7mZlm9p0IPz4XYTCw/export?format=csv&gid=0"
)

SENDER_EMAIL = os.environ.get("SENDER_EMAIL", "mtrwa.office@gmail.com")
APP_PASSWORD = os.environ.get("APP_PASSWORD", "ybpmuratzunwiejv")

APPOINTED_RECIPIENTS = [
    "deepakdhawan@mani-group.com",
    "Pallav@mani-group.com",
    "mtrwa.office@gmail.com"
]

MEMBERS_CSV_URL = os.environ.get(
    "MEMBERS_CSV_URL",
    "https://docs.google.com/spreadsheets/d/1cZ7N52nVw9yy3QpsMh1Kra9-yk7mZlm9p0IPz4XYTCw/export?format=csv&gid=1248655544"
)

dispatched = {"14LD", "4LA", "6LB", "101", "11CD", "12LB", "1JB", "10NA", "2KC", "14BB", "3JC", "4DC", "13DB"}

def load_members_from_cloud():
    members = {}
    try:
        req = urllib.request.Request(MEMBERS_CSV_URL, headers={"User-Agent": "Mozilla/5.0"})
        with urllib.request.urlopen(req, timeout=15) as resp:
            content = resp.read().decode("utf-8")
            reader = list(csv.reader(io.StringIO(content)))
            for r in reader[1:]:
                if len(r) >= 3:
                    f_no = r[1].strip().upper()
                    if f_no:
                        members[f_no] = {
                            "name": r[0].strip(),
                            "email": r[2].strip()
                        }
        print(f"[+] Loaded {len(members)} society members dynamically from Google Sheets!")
    except Exception as e:
        print(f"[-] Could not load members from cloud sheet: {e}")
    return members

def generate_html(v):
    return f"""
    <html>
      <head>
        <style>
          body {{ font-family: Helvetica, Arial, sans-serif; color: #222; margin: 25px; line-height: 1.5; }}
          h2 {{ color: #0b57d0; border-bottom: 2px solid #0b57d0; padding-bottom: 6px; margin-bottom: 15px; }}
          table {{ width: 100%; border-collapse: collapse; margin-top: 15px; }}
          th, td {{ border: 1px solid #ccc; padding: 10px; text-align: left; font-size: 13px; }}
          th {{ background-color: #f2f4f8; font-weight: bold; width: 35%; }}
          .badge {{ display: inline-block; padding: 4px 8px; border-radius: 4px; background-color: #e6f4ea; color: #137333; font-weight: bold; font-size: 11px; }}
        </style>
      </head>
      <body>
        <h2>MANI TRIBHUVAN – SETTLEMENT POLL RESPONSE RECORD</h2>
        <p><strong>Status:</strong> <span class="badge">{v.get('status', 'LOCKED')}</span> &nbsp;|&nbsp; <strong>Recorded at:</strong> {v.get('timestamp', time.strftime('%d/%m/%Y, %I:%M %p'))}</p>
        <table>
          <tr><th>Name</th><td>{v.get('name', 'Society Member')}</td></tr>
          <tr><th>Email Address</th><td>{v.get('email', '')}</td></tr>
          <tr><th>Flat No.</th><td><strong>{v.get('flat_no', '')}</strong></td></tr>
          <tr><th>Response Selection</th><td><strong style="color:#0b57d0;">{v.get('vote', '')}</strong></td></tr>
          <tr><th>Comments / Reasons</th><td>{v.get('comments', 'None')}</td></tr>
          <tr><th>IP Address</th><td>{v.get('ip', 'Not Detected')}</td></tr>
          <tr><th>Device Signature</th><td>{v.get('device', 'Web Browser')}</td></tr>
        </table>
        <br/>
        <p style="font-size: 11px; color: #777;">Official response record generated by Mani Tribhuvan Settlement Management System.</p>
      </body>
    </html>
    """

def send_notifications_for_vote(v):
    flat_no = v.get("flat_no", "")
    name = v.get("name", "")
    member_email = v.get("email", "")

    subject = f"MANI TRIBHUVAN: Settlement Poll Response Recorded (Flat {flat_no} - {name})"
    html_body = generate_html(v)

    try:
        server = smtplib.SMTP("smtp.gmail.com", 587, timeout=30)
        server.ehlo()
        server.starttls()
        server.ehlo()
        server.login(SENDER_EMAIL, APP_PASSWORD)
    except Exception as e:
        print(f"[-] SMTP Connection Error: {e}")
        if "5.4.5" in str(e) or "sending limit" in str(e).lower():
            return "LIMIT_EXCEEDED"
        return False

    success = True
    for to_email in APPOINTED_RECIPIENTS:
        try:
            msg = MIMEMultipart("alternative")
            msg["From"] = f"Mani Tribhuvan Settlement System <{SENDER_EMAIL}>"
            msg["To"] = to_email
            msg["Subject"] = subject
            msg["Date"] = formatdate(localtime=True)
            msg["Message-ID"] = make_msgid(domain="gmail.com")
            msg["Reply-To"] = SENDER_EMAIL
            msg.attach(MIMEText(html_body, "html", "utf-8"))
            server.sendmail(SENDER_EMAIL, [to_email], msg.as_string())
            print(f"[+] Delivered Flat {flat_no} -> {to_email}")
        except Exception as e:
            print(f"[-] Error delivering Flat {flat_no} to {to_email}: {e}")
            if "5.4.5" in str(e) or "sending limit" in str(e).lower():
                try: server.quit()
                except: pass
                return "LIMIT_EXCEEDED"
            success = False

    if member_email and "@" in member_email:
        try:
            msg_v = MIMEMultipart("alternative")
            msg_v["From"] = f"Mani Tribhuvan Residents Welfare Association <{SENDER_EMAIL}>"
            msg_v["To"] = member_email
            msg_v["Subject"] = f"MANI TRIBHUVAN: Settlement Poll Response Recorded (Flat {flat_no})"
            voter_body = f"<p>Dear Member,</p><p>Thank you. Your response on the Draft Settlement Agreement has been recorded for Flat <strong>{flat_no}</strong>.</p><hr/>" + html_body
            msg_v.attach(MIMEText(voter_body, "html", "utf-8"))
            server.sendmail(SENDER_EMAIL, [member_email], msg_v.as_string())
            print(f"[+] Delivered confirmation receipt -> {member_email}")
        except Exception as e:
            print(f"[-] Error delivering receipt to {member_email}: {e}")

    try:
        server.quit()
    except Exception:
        pass

    return success

def background_worker():
    print("=======================================================")
    print("  MANI TRIBHUVAN: CLOUD DISPATCHER DAEMON RUNNING 24/7")
    print(f"  Sender: {SENDER_EMAIL}")
    print("=======================================================\n")

    members_map = load_members_from_cloud()

    while True:
        try:
            req = urllib.request.Request(SHEET_EXPORT_URL, headers={"User-Agent": "Mozilla/5.0"})
            with urllib.request.urlopen(req, timeout=15) as resp:
                content = resp.read().decode("utf-8")
                rows = list(csv.reader(io.StringIO(content)))
                
                if rows:
                    for r in rows[1:]:
                        if len(r) < 4:
                            continue
                        timestamp = r[0].strip()
                        email = r[1].strip()
                        flat_no = r[2].strip().upper()
                        vote = r[3].strip()
                        comments = r[4].strip() if len(r) > 4 else "None"
                        ip = r[5].strip() if len(r) > 5 else "Not Detected"
                        device = r[6].strip() if len(r) > 6 else "Web Browser"
                        status = r[7].strip() if len(r) > 7 else "LOCKED"

                        if not flat_no:
                            continue

                        if flat_no not in dispatched:
                            member_info = members_map.get(flat_no, {})
                            member_name = member_info.get("name", "Society Member")
                            effective_email = email or member_info.get("email", "")

                            vote_obj = {
                                "name": member_name,
                                "email": effective_email,
                                "flat_no": flat_no,
                                "vote": vote,
                                "comments": comments,
                                "ip": ip,
                                "device": device,
                                "status": status,
                                "timestamp": timestamp
                            }

                            print(f"[*] NEW VOTE DETECTED: Flat {flat_no} ({member_name})! Dispatching...")
                            res = send_notifications_for_vote(vote_obj)
                            if res == "LIMIT_EXCEEDED":
                                print("[!] Gmail 24-hour limit cooling down. Sleeping for 15 minutes...")
                                time.sleep(900)
                                break
                            elif res:
                                dispatched.add(flat_no)
                                print(f"[+] Flat {flat_no} completely notified!\n")
                            else:
                                time.sleep(10)
        except Exception as e:
            print(f"[-] Cloud loop error: {e}")

        time.sleep(20)

class HealthCheckHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        res = {
            "status": "healthy",
            "service": "Mani Tribhuvan Settlement Poll Cloud Dispatcher",
            "dispatched_count": len(dispatched),
            "sender": SENDER_EMAIL
        }
        self.wfile.write(json.dumps(res).encode("utf-8"))

    def log_message(self, format, *args):
        return # Silence standard HTTP access logs

def start_server():
    port = int(os.environ.get("PORT", 10000))
    server = HTTPServer(("0.0.0.0", port), HealthCheckHandler)
    print(f"[+] Healthcheck HTTP Server listening on port {port}...")
    server.serve_forever()

if __name__ == "__main__":
    t = threading.Thread(target=background_worker, daemon=True)
    t.start()
    start_server()
